Our bootcamps
kodemia/website.kodemia.mx pull request #10
Opened 2020-10-27 06:05 UTC by arianaomi

sección nuestros bootcamps 
👀

2020-10-27 06:32 UTC, devCharles commented on components/Pages/Home/OurBootcamps.tsx
> +            ))
aqui no recomiendo que usemos la deconstrucción es mas claro ver que dice `modality.name` a ver que solo dice name

2020-10-27 07:14 UTC, rrortegaa requested changes
Te dejé unos comentarios :speech_balloon:

2020-10-27 16:00 UTC, arianaomi commented on components/Navbar.tsx
> +              src='/icons/kodemia-logo-02.svg'
No, mejor hay que manejarlos así con mayúscula

2020-10-27 19:09 UTC, devCharles approved these changes

2020-10-28 02:53 UTC, rrortegaa requested changes
Aquí solo te dejé comentarios de cambios menores

2020-10-28 02:53 UTC, rrortegaa commented on components/LanguageCard.tsx
> +  lenguage: string,
Aquí también language :stuck_out_tongue_closed_eyes:

2020-10-28 02:53 UTC, rrortegaa commented on components/LanguageCard.tsx
> +  lenguage,
Aquí también porfi

2020-10-28 02:53 UTC, rrortegaa commented on components/LanguageCard.tsx
> +      <H2 whiteText={name} cyanText={lenguage} />
y aquí

2020-10-28 02:53 UTC, rrortegaa commented on styles/variables.scss
> +$content-max-width: 1200px;
:clap:

2020-10-28 02:53 UTC, rrortegaa commented on styles/pages/Home/our-bootcamps.scss
> +    .modalities-conteiner {
aquí: modalities-container

2020-10-28 02:53 UTC, rrortegaa commented on styles/components/navbar.scss
> +  .container { // TODO: arreglar xD
:heart:  
Ah! mejor sin el comentario :wink:

2020-10-28 02:53 UTC, rrortegaa commented on pages/index.tsx
> +    <>
:sunglasses:

2020-10-28 02:53 UTC, rrortegaa commented on components/Navbar.tsx
> +                src='/icons/Kodemia-logo-02.svg'
Acá en minúsculas: Kodemia-logo-02.svg, cierto?

2020-10-28 02:53 UTC, rrortegaa commented on components/Pages/Home/OurBootcamps.tsx
> +          lenguage={Bootcamps.javascript.language}
aquí también, language

2020-10-28 02:53 UTC, rrortegaa commented on components/Pages/Home/OurBootcamps.tsx
> +        <div className='modalities-conteiner'>
acá, modalities-container

2020-10-28 02:53 UTC, rrortegaa commented on components/Pages/Home/OurBootcamps.tsx
> +          lenguage={Bootcamps.python.language}
language en ésta prop

2020-10-28 02:53 UTC, rrortegaa commented on components/Pages/Home/OurBootcamps.tsx
> +        <div className='modalities-conteiner'>
modalities-container

2020-10-28 22:19 UTC, devCharles commented
Se rompieron las imagenes, supone que es por el cambio de case de la carpeta

El problema es que tanto windows como macOS son case insensitive por defecto
entonces no detectan los cambios de mayusculas y minusculas que se hacen en los nombres de carpeta o archivos

aca te dejo la solucion explicada
https://stackoverflow.com/questions/10523849/changing-capitalization-of-filenames-in-git/16071375

2020-10-28 22:24 UTC, devCharles commented on components/Navbar.tsx
> +            className={`navbar-burger burger ${isActive ? 'is-active' : ''}`}
aca deberiamos usar classnames

2020-10-28 22:24 UTC, devCharles commented on components/Navbar.tsx
> +        <div className={`navbar-menu ${isActive ? 'is-active' : ''}`}>
classnames aqui tambien

2020-10-28 22:27 UTC, devCharles commented on components/Pages/Home/Hero.tsx
> +            title='Transforma tu vida programando' content='Más que una escuela, somos el aliado que te acompaña para desarrollarte como programador, antes, durante y después de nuestros Bootcamps. '
aca, recuerda que es preferible partir estas lineas largas en varias lineas para que sea mas legible

2020-10-30 01:35 UTC, rrortegaa approved these changes

2020-10-30 06:22 UTC, devCharles commented on styles/variables.scss
> +$content-min-width: 719px;
para que necesitamos esta variable?

2020-10-30 06:24 UTC, arianaomi commented on styles/variables.scss
> +$content-min-width: 719px;
para ajustar el footer fue necesario ponerle ese minimo, pero voy a checar si con la clase que creo Rose ya no es necesario lo elimino.

2020-10-30 06:26 UTC, devCharles commented on styles/variables.scss
> +$content-min-width: 719px;
vale

2020-10-30 06:27 UTC, devCharles approved these changes

2020-10-30 06:34 UTC, merged