add components
kodemia/website.kodemia.mx pull request #101
Opened 2021-11-17 22:28 UTC by arianaomi

-add Footer
- add form

2021-11-18 16:50 UTC, devCharles requested changes

2021-11-18 16:50 UTC, devCharles commented on components/Forms/ApplyLandingForm.tsx
> +			campaignName: 'website'
podemos cambiar aquí por "landing" @arianaomi

2021-11-18 16:52 UTC, arianaomi commented on components/Forms/ApplyLandingForm.tsx
> +			campaignName: 'website'
yepas

2021-11-19 01:11 UTC, devCharles requested changes

2021-11-19 01:11 UTC, devCharles commented on pages/[...page].tsx
> +	console.log('Builder', props.content)
Console log

2021-11-19 02:10 UTC, arianaomi commented on pages/[...page].tsx
> +	console.log('Builder', props.content)
😲

2021-11-19 02:16 UTC, devCharles approved these changes

2021-11-19 02:18 UTC, merged