add tracker on event button
kodemia/website.kodemia.mx pull request #114
Opened 2021-12-07 04:15 UTC by arianaomi

- Create a tracker Event function
- Add function on the event button

2021-12-07 05:57 UTC, devCharles requested changes
@arianaomi

2021-12-07 05:57 UTC, devCharles commented on lib/tracker.ts
> +export function onEventButtonClicked (buttonName: string){
Por que `buttonName`?

2021-12-07 05:57 UTC, devCharles commented on components/CardEvent.tsx
> +          onClick={()=> tracker.onEventButtonClicked(btnLabel)}
Por que el `btnLabel` como parametro ?

2021-12-07 06:08 UTC, arianaomi commented on lib/tracker.ts
> +export function onEventButtonClicked (buttonName: string){
para saber si es de un evento privado o no

2021-12-10 06:28 UTC, devCharles requested changes

2021-12-10 06:28 UTC, devCharles commented on components/CardEvent.tsx
> +export default function Card({ event, className }: Props) {
Podemos re-nombrar esto? debería ser CardEvent

2021-12-10 06:28 UTC, devCharles commented on types/common.ts
> +}
Falta la linea del final de este archivo

2021-12-10 06:32 UTC, arianaomi commented on components/CardEvent.tsx
> +export default function Card({ event, className }: Props) {
😓

2021-12-10 07:09 UTC, devCharles approved these changes

2021-12-10 07:13 UTC, devCharles commented
🙌🏼

2021-12-10 17:31 UTC, merged