Mentors page
kodemia/website.kodemia.mx pull request #119
Opened 2021-12-21 20:51 UTC by rrortegaa

2022-01-11 20:31 UTC, arianaomi commented on components/MentorCard.tsx
> +        {`Experiencia: ${mentor.yearsOfExperience} años`}
Deberiamos checar si es 1 año ¿?

2022-01-12 21:38 UTC, devCharles commented on components/MentorCard.tsx
> +          target='_blank'
Que pasa si no tenemos alguno de estos links?
No debería renderizar el logo de la red social si no lo tenemos

2022-01-12 22:29 UTC, arianaomi submitted a review, later dismissed

2022-01-13 05:07 UTC, arianaomi commented on components/MentorCard.tsx
> +          target='_blank'
Duda: Aqui deberiamos verificar si es solo el usurio o toda la liga o  en builder poner tal cual que solo es el usuario. ?

2022-01-13 05:10 UTC, devCharles commented on components/MentorCard.tsx
> +          target='_blank'
En builder aclarar que solo es el usuario

2022-01-17 17:13 UTC, devCharles requested changes

2022-02-25 16:25 UTC, devCharles approved these changes

2022-02-25 16:38 UTC, merged