♻️  Headings refactor
kodemia/website.kodemia.mx pull request #123
Opened 2022-01-26 07:06 UTC by rrortegaa

- :recycle: deleted Bulma
- :recycle: TODO commnets in style files
- :recycle: delete screens variables in mixins file
- :recycle: resolve conflict in index.scss
- :recycle: updated classes in Button component
- :recycle: deleted style file and index.scss import
- :arrow_up: Upgraded to Tailwind 3.0
- :arrow_up: deleted prefix class and added template files paths into content class
- :wrench: added design system classes and custom component
- fix typo
- fix typos
- fix typos
- :lipstick: added tailwind classes to button component
- :lipstick: added style classes
- :recycle: deleted comments
- :recycle: deleted last comments
- :recycle: refactor H1 component
- :recycle: refactor H2 component
- :recycle: refactor H3 component
- :recycle: refactor H3 component & fix typo in H2 component
- :recycle: refactor H4 component
- :recycle: refactor H5 component
- :recycle: fix typos into  H5 component
- :hammer: added new H6 component
- :hammer: added new Body component for headings
- :hammer: added new Subtitle component for headings
- :pencil2: fix typos into Body component

2022-01-26 07:40 UTC, devCharles requested changes

2022-01-26 07:40 UTC, devCharles commented on components/Body.tsx
> +export default function Body ({ children }: Props):JSX.Element {
Cambiemos este componente por Text, Body no es un buen nombre

2022-01-26 07:40 UTC, devCharles commented on components/Subtitle.tsx
> +export default function Subtitle ({ children, isWhite }: Props):JSX.Element {
Eliminemos este componente

2022-01-26 07:40 UTC, devCharles commented on tailwind.config.js
> +        'brand-subtitle': ['20px', '1.4'],
Eliminemos esta configuración también

2022-01-26 07:40 UTC, devCharles commented on tailwind.config.js
> +        'brand-body': ['16px', '1.5']
Cambiemos este por body-text para que haga match con el componente

2022-01-26 07:40 UTC, devCharles commented on components/H1.tsx
>  import TextCursor from './TextCursor'
Puedes arreglar este import porfa?

2022-01-26 07:40 UTC, devCharles commented on components/H2.tsx
>  import TextCursor from './TextCursor'
Tambien arreglemos este

2022-01-26 07:40 UTC, devCharles commented on components/H3.tsx
>  import TextCursor from './TextCursor'
Otro mas por arreglar

2022-01-26 07:52 UTC, rrortegaa commented on tailwind.config.js
> +        'brand-body': ['16px', '1.5']
yep

2022-01-29 05:47 UTC, devCharles requested changes
YEAH! es un monton de css borrado 🎉 

Esta quedando genial!! 👍🏼 

Solo dejo algunos comments

2022-01-29 05:47 UTC, devCharles commented on components/H3.tsx
> +  isFirstCyan?: Boolean
debería ser `boolean` con minuscula

https://www.typescriptlang.org/docs/handbook/2/everyday-types.html

2022-01-29 05:47 UTC, devCharles commented on components/H5.tsx
> +  isWhite?: Boolean
Cambiar a minuscula

2022-01-29 05:47 UTC, devCharles commented on components/H6.tsx
> +  isWhite?: Boolean
same here

2022-01-29 05:47 UTC, devCharles commented on components/Pages/Classes/Klass.tsx
> +import VideoPlayer from './VideoPlayer'
Puedes arreglar estos imports porfa?

2022-01-29 06:04 UTC, devCharles approved these changes

2022-01-29 06:13 UTC, merged