Refactor footer
kodemia/website.kodemia.mx pull request #128
Opened 2022-02-23 07:11 UTC by arianaomi

- Removed bulma in the footer
- Tried to refactor the code

2022-02-23 22:26 UTC, rrortegaa requested changes
Te dejé varios comentarios, creo que debes revisar la configuración de tu linter, está dejando algunos espacios y quitando otros

2022-02-23 22:26 UTC, rrortegaa commented on components/Footer.tsx
> +    </footer >
quitar el espacio antes de >

2022-02-23 22:26 UTC, rrortegaa commented on components/Footer.tsx
> +          className={classNames('w-44')}
no es necesario poner classNames aquí, solo pasar el _width_ a className

2022-02-23 22:26 UTC, rrortegaa commented on components/Footer.tsx
> +            <div >
quitar espacio antes de _>_

2022-02-23 22:26 UTC, rrortegaa commented on components/Footer.tsx
> +            <div >
quitar espacio antes de _>_

2022-02-23 22:26 UTC, rrortegaa commented on components/Footer.tsx
> +            <div className={classNames('my-7')}>
no es necesario poner classNames aquí, solo pasar el _margin_ a className

2022-02-23 22:26 UTC, rrortegaa commented on components/Footer.tsx
> +            'md:items-start md:justify-between'
pasar _items-center_ a la siguiente linea junto con las clases definidas para tablet

2022-02-23 22:26 UTC, rrortegaa commented on components/Footer.tsx
> +                  className={classNames('mr-5')}
no es necesario poner classNames aquí, solo pasar el _margin_ a className

2022-02-24 07:17 UTC, devCharles approved these changes

2022-02-24 19:01 UTC, merged