Refactor-transform your life
kodemia/website.kodemia.mx pull request #129
Opened 2022-02-24 06:38 UTC by arianaomi

- Removed bulma on Transform your life section

2022-02-25 10:41 UTC, rrortegaa requested changes
Nao, te dejé un par de comentarios 👀

2022-02-25 10:41 UTC, rrortegaa commented on components/Pages/Home/TransformYourLife.tsx
> +    <section>
- me parece que esta etiqueta _section_ es redundante, el componente PageSection ya incluye una, sería mejor quitarla

2022-02-25 10:41 UTC, rrortegaa commented on components/Pages/Home/TransformYourLife.tsx
> +        contentClassName='md:flex md:justify-between md:items-center '
borrar el espacio antes de _'_al final de la línea

2022-02-25 11:01 UTC, devCharles requested changes
@arianaomi Puedes actualizar esta rama para que se vean los cambios de footer también porfa?

2022-03-01 10:23 UTC, devCharles approved these changes

2022-03-01 17:12 UTC, merged