Refactor/navbar
kodemia/website.kodemia.mx pull request #132
Opened 2022-02-25 08:58 UTC by arianaomi

-  Bulma was removed from the navbar

2022-02-25 11:41 UTC, devCharles requested changes

2022-02-25 11:41 UTC, devCharles commented on tailwind.config.js
> +          transparent:'rgba(24, 24, 24, 0.9)'
en lugar de agregar aquí el transparent, no podemos usar un color que ya tenemos y agregar solo un opacity diferente? 🤔

2022-02-25 11:41 UTC, devCharles commented on components/Navbar.tsx
> +                " after:content-[' '] after:absolute after:rotate-45 after:bg-brand-complementary after:w-[1px] after:h-4 after:mt-1",
```suggestion
                "after:content-[' '] after:absolute after:rotate-45 after:bg-brand-complementary after:w-[1px] after:h-4 after:mt-1",
```

2022-02-25 14:05 UTC, rrortegaa requested changes

2022-02-25 14:05 UTC, rrortegaa commented on tailwind.config.js
> +          transparent:'rgba(24, 24, 24, 0.9)'
- Justo eso iba a sugerir, sería poner la clase del color _brand-black_ y _opacity-90_, en este caso

2022-02-25 14:05 UTC, rrortegaa commented on components/Navbar.tsx
> +      'bg-brand-black-transparent',
- _bg-brand-black_ y _opacity-90_

2022-03-01 01:40 UTC, rrortegaa requested changes
Nao, te dejé unos comentarios

2022-03-01 10:31 UTC, devCharles approved these changes

2022-03-01 12:42 UTC, rrortegaa approved these changes

2022-03-01 17:15 UTC, merged