Refactor inputs
kodemia/website.kodemia.mx pull request #138
Opened 2022-03-01 05:39 UTC by arianaomi

- remove bulma in inputs components.

2022-03-03 09:34 UTC, devCharles requested changes

2022-03-03 09:34 UTC, devCharles commented on tailwind.config.js
> +  important: true,
Por que es necesario que se use el important?

2022-03-03 09:35 UTC, devCharles requested changes
Así se ve el dropdown cuando esta abierto, hay que arreglarlo

![Screen Shot 2022-03-03 at 3 34 46](https://user-images.githubusercontent.com/7495937/156537359-ab727ec1-81b3-4ba5-a9e4-f89ca9d8d101.png)

2022-03-03 21:05 UTC, rrortegaa commented on components/Inputs/Input.tsx
> +        'mb-2 font-normal ',
- quitar el espacio antes de la _'_ final

2022-03-03 21:06 UTC, rrortegaa commented on components/Inputs/TextArea.tsx
> +        'mb-2 font-normal ',
- quitar el espacio antes de la _'_ final

2022-03-03 21:07 UTC, rrortegaa commented on components/Inputs/PhoneInput.tsx
> +        'mb-2 font-normal ',
- quitar el espacio antes de la _'_ final

2022-03-03 21:27 UTC, rrortegaa reviewed
Nao, te dejé algunos comentarios

2022-03-06 07:53 UTC, arianaomi commented on tailwind.config.js
> +  important: true,
Para poder modificar el bg de la bandera del boton de telefono

2022-03-08 05:12 UTC, rrortegaa approved these changes

2022-03-08 09:25 UTC, devCharles approved these changes

2022-03-08 15:48 UTC, merged