Refactor login
kodemia/website.kodemia.mx pull request #141
Opened 2022-03-07 05:47 UTC by arianaomi

- Bulma was removed in login view and form.

2022-03-07 05:52 UTC, arianaomi commented on components/Pages/Login/LoginForm.tsx
> +      <ToastContainer position='top-center' style={{marginTop:'54px'}}/>
⚠️ Tengo un problema con el navbar y el toast (aparece por debajo del navbar)

2022-03-07 08:04 UTC, devCharles requested changes
Oye en el video mas o menos cuando se ve que sale caro me empieza a parpadear, no te pasa a ti tambien?

2022-03-07 08:04 UTC, devCharles commented on components/Pages/Login/LoginForm.tsx
> +      <ToastContainer position='top-center' style={{marginTop:'54px'}}/>
creo que por ahora podemos ignorarlo y ver si podemos hacer algo después

2022-03-08 05:25 UTC, rrortegaa requested changes

2022-03-08 05:25 UTC, rrortegaa commented on components/Pages/Login/LoginForm.tsx
> +            'focus:border focus:border-solid focus:border-brand-primary',
```suggestion
            'focus:outline focus:outline-1 focus:outline-brand-primary',
```
- Me parece que puedes aplicar esto 👆🏻 para que no se vea ese color azulito en los inputs al hacerles focus
- Así tampoco se moverían los inputs y sus labels 2 px hacia abajo cuando al hacerles focus se agrega el border

2022-03-08 08:48 UTC, rrortegaa approved these changes

2022-03-08 09:33 UTC, devCharles approved these changes
🚀

2022-03-08 15:48 UTC, merged