Refactor/alliances kodemia
kodemia/website.kodemia.mx pull request #149
Opened 2022-03-09 08:11 UTC by evcorona

Preview

2022-03-09 20:58 UTC, rrortegaa requested changes
Elda, te dejé un par de comentarios

2022-03-09 20:58 UTC, rrortegaa commented on components/Pages/Home/AlliancesKodemia.tsx
> +            "alliances-kodemia-container section-container",
- Contamos con un componente llamado `PageSection` que nos proporciona el _width_ y _paddings_ para la sección y el _width_ para el contenido, me parece que podrías sustituir este _div_ y el _div_ padre con ese componente.

- Si necesitas agregar mas clases, `PageSection` tiene dos props: _SectionClassName_ y _ContentClassName_ dónde puedes agregarlas

2022-03-09 20:58 UTC, rrortegaa commented on components/CarrouselAlliances.tsx
>          'carrousel-alliances',
- Si aún no deseas eliminar las clases custom, ni los archivos .scss asociados como en este caso, _carrousel-alliances_, ¿Podrías comentarlas? Porque crea un poco de confusión al revisar los archivos, parece que algunas clases siguen en uso pero en el css están comentadas 😵‍💫

2022-03-09 20:58 UTC, rrortegaa commented on components/CarrouselAlliances.tsx
>          'carrousel-alliances',
- Si aún no deseas eliminar las clases custom, ni los archivos .scss asociados como en este caso, _carrousel-alliances_, ¿Podrías comentarlas? Porque crea un poco de confusión al revisar los archivos, parece que algunas clases siguen en uso pero en el css están comentadas 😵‍💫

2022-03-09 21:41 UTC, evcorona commented on components/Pages/Home/AlliancesKodemia.tsx
> +            "alliances-kodemia-container section-container",
Gracias Rose, listo lo he agregado

2022-03-09 21:41 UTC, evcorona commented on components/CarrouselAlliances.tsx
>          'carrousel-alliances',
Gracias Rose, las necesitaba para validar que estaba migrando todo y revisar con Nao. Ya las he borrado.

2022-03-09 21:41 UTC, evcorona commented on components/CarrouselAlliances.tsx
>          'carrousel-alliances',
Gracias Rose, las necesitaba para validar que estaba migrando todo y revisar con Nao. Ya las he borrado.

2022-03-10 00:24 UTC, rrortegaa requested changes
Te dejé un par de comentarios

2022-03-10 00:24 UTC, rrortegaa commented on components/Pages/Home/AlliancesKodemia.tsx
> +      <div className="max-w-48 lg:max-w-full">
- ¿Podrías checar la configuración de comillas en tu editor?  En algunas partes te pone comillas simples y en otras dobles

2022-03-10 03:32 UTC, evcorona commented on components/Pages/Home/AlliancesKodemia.tsx
> +            "alliances-kodemia-container section-container",
Gracias Rose ya quedo cambiado.

2022-03-10 03:33 UTC, evcorona commented on components/Pages/Home/AlliancesKodemia.tsx
> +      <div className="max-w-48 lg:max-w-full">
Muchas gracias Rose. Ya lo corregi fue un error, me guie en los parametros incorrectos de width.

2022-03-10 03:33 UTC, evcorona commented on components/Pages/Home/AlliancesKodemia.tsx
> +      <div className="max-w-48 lg:max-w-full">
Resuelto

2022-03-10 04:02 UTC, devCharles requested changes
👀

2022-03-10 04:02 UTC, devCharles commented on components/CarrouselAlliances.tsx
> +        `${!hasContent && 'before:content-none after:content-none'}`,
A classnames le puedes pasar un objeto en cualquiera de sus parametros, si el valor de la key es verdadero, renderiza la key como una clase, si el valor es falsy no se renderiza nada, entonces debería quedar algo así:

```suggestion
        { 'before:content-none after:content-none': !hasContent }
```

Así como lo vemos en [su documentación](https://www.npmjs.com/package/classnames)

2022-03-10 17:00 UTC, devCharles approved these changes
LGTM

2022-03-10 19:00 UTC, arianaomi approved these changes
🚀

2022-03-10 21:55 UTC, rrortegaa approved these changes
🚀

2022-03-10 21:57 UTC, merged