thank you page
kodemia/website.kodemia.mx pull request #152
Opened 2022-03-11 04:42 UTC by arianaomi

## PR Description

- Feature: Removed bulma on thank you page

## Additional

- URL: /empresas/registro/gracias

### Screen Shots/Recordings

### Related Issues/Tickets

## Notes

Be sure to add if needed

- Tests
- Types
- Documentation

2022-03-11 05:18 UTC, rrortegaa commented on pages/empresas/registro/gracias.tsx
> +        <div className='bg-brand-black-light flex flex-col items-center justify-center rounded-medium h-64 p-6 md:w-2/3 md:mx-auto'>
¿Qué opinas si en lugar de cambiar en `md` cambie en `sm`? porque en el tamaño mas grande de mobile se ve muy ancha 🤔

![Screen Shot 2022-03-10 at 23 15 29](https://user-images.githubusercontent.com/20275714/157806842-7714ef0f-0cb3-49bb-9825-578121e839e9.png)

2022-03-11 05:43 UTC, rrortegaa commented on pages/aplicar/gracias/[bootcamp].tsx
> +        <div className={classNames(
- Aquí podrías utilizar el componente `Card` y no ponerle `isBordered`, creo que sólo le pasarías el background y el border-radius `wide` (30px)

2022-03-11 05:43 UTC, rrortegaa commented on pages/empresas/registro/gracias.tsx
> +        <div className={classNames(
- Lo mismo que 👆🏻

2022-03-11 08:24 UTC, rrortegaa requested changes
Nao, te deje unos comentarios

2022-03-11 08:24 UTC, rrortegaa commented on pages/aplicar/gracias/[bootcamp].tsx
> +        <div className={classNames(
- Nao, me quedé con la duda, ¿Para estas cards (thank you) nos funciona usar el componente `Card` o no? 🤔

2022-03-22 03:09 UTC, devCharles approved these changes
LGTM

2022-03-22 19:21 UTC, rrortegaa approved these changes

2022-03-22 19:23 UTC, evcorona approved these changes
🚀

2022-03-23 00:15 UTC, merged