:recycle: Hero Companies refactor
kodemia/website.kodemia.mx pull request #154
Opened 2022-03-11 09:20 UTC by rrortegaa

- :recycle: deleted Bulma
- :recycle: TODO commnets in style files
- :recycle: delete screens variables in mixins file
- :recycle: resolve conflict in index.scss
- :recycle: updated classes in Button component
- :recycle: deleted style file and index.scss import
- :arrow_up: Upgraded to Tailwind 3.0
- :arrow_up: deleted prefix class and added template files paths into content class
- :wrench: added design system classes and custom component
- fix typo
- fix typos
- fix typos
- :lipstick: added tailwind classes to button component
- :lipstick: added style classes
- :recycle: deleted comments
- :recycle: deleted last comments
- :recycle: refactor TextCursor component
- :twisted_rightwards_arrows: before merge with changes in button-refactor branch
- :lipstick: erase text-cursor.scss file
- :lipstick: erase text-cursor.scss file in index
- :recycle: refactor H1 component
- :recycle: refactor H2 component
- :recycle: refactor H3 component
- :recycle: refactor H3 component & fix typo in H2 component
- :recycle: refactor H4 component
- :recycle: refactor H5 component
- :recycle: fix typos into  H5 component
- :hammer: added new H6 component
- :hammer: added new Body component for headings
- :hammer: added new Subtitle component for headings
- :pencil2: fix typos into Body component
- :art: added requested changes
- :art: added requested changes
- :art: added requested changes
- :art: fix issues with TextCursor into registry and thankyou pages
- :recycle: refactor BootcampCard component
- :recycle: refactor HeroCard component
- :recycle: refactor LanguageCard component
- :pencil2: fix typos
- :pencil2: fix typos
- :pencil2: fix typos
- :art: added requested changes
- :recycle: part-1 of refactor InfoCard component
- :recycle: refactor HeroCard component
- :recycle: refactor Text & H6 components
- :recycle: refactor tailwind config
- :recycle: refactor BootcampCard component
- :recycle: part-1 of refactor TestimonialCard component
- :recycle: refactor InfoCard component
- :pencil2: fix typo into H1 component
- :pencil2: fix typo into EventCard name component
- :pencil2: changed to EventCard name component
- :pencil2: fix typos into eventos page
- :recycle: deleted comments into InfoCard component
- :recycle: refactor LanguageCard component
- :pencil2: fix typos into OurBootcamp component
- :art: added bg color for fix sections
- :recycle: refactor TestimonialCard component
- :recycle: refactor Testimonials section
- :recycle: refactor project section-content
- check the styles
- added body background
- :recycle: refactor project section-container and content-wrapper
- :pencil2: fix typos section-container and content-wrapper
- :bug: eslint bug
- :pencil2: fix typos into tailwind.config
- :lipstick: added new PageContainer component
- :lipstick: implemented PageContainer component into WhyKodemia section
- :lipstick: added className prop into PageSection component
- :pencil2: fix typos into PageSection component and into package.json
- :lipstick: added sectionClassName and contentClassName props into PageSection component
- :pencil2: fix typos into WhyKodemia section
- remove bulma from footer
- reusing code and styles
- reusing styles
- refactor code
- single
- :sparkles: added Card component
- :pencil2: fix typos into tailwind.config
- :recycle: implemented new Card component into BootcampCard
- :pencil2: fix typos into TestimonialCard component
- :recycle: implemented new Card component into EventCard
- :recycle: refactored eventos page with new PageSection component
- :label: renamed class and fix date type prop
- rename variables
- upgrate the config files
- :pencil2: fix typos into Card component
- lint
- remove spaces
- removes spaces
- remove bulma
- update size of buttons
- rename
- :bug: fix background image in eventos page
- :bug: fix EventCard bug with justify content
- Kodemia financing
- fix container size
- removed margin bottom
- first commit style
- navbar 90%
- full navbar
- Bulma was removed from the navbar
- ups
- :pencil2: fix typos into PageSection component
- :recycle: refactored WhyKodemia section with PageSection and InfoCard components
- :recycle: refactored OurBootcamps section with PageSection, LanguageCard and BootcampCard components
-  remove de new transparent color
- Added a bg on gray button
- added pinter
- removed section tag
-  refactor imports
- :bug: return Testimonial section to his original version
- :pencil2: fix typos into utilities.scss
- update image path
-  :)
- :pencil2: fix typos into LanguageInfo component
- :bug: fix node_modules
- inputs
-  remove space and console.log
-  remove flag background
- remove bulma on inputs
- update name
- add classNames
- name
- check test
- test
- comment phone-dropdown class
- :recycle: refactored InfoElement component
- :recycle: refactored OurMethod section in Home page
- :recycle: refactored TalenDevelopment section in Companies page
- :recycle: refactored HelpFindTalent section in Companies page
- :recycle: refactored Eventos page
- fix width
- create a component style file
- fix
-  remove files
- :lipstick: updated margin and alignment in both sections
- :bug: fix FindIdealKoder section
- :bug: fix KodemiaFinancing section and Events image
- grid cols fix
- fic Eventos page
- :bug: fix FindIdealKoder section and InfoBullet component
- :lipstick: fix detail into InfoBullet component
- :lipstick: fix detail into InfoBullet component
- :twisted_rightwards_arrows: after merge with project-refactor branch update
- :recycle: refactored Metrics section into javascript page and MetricCard component
- :recycle: refactored Scholarship section into javascript page
- fixed font color
- remove margin
- look
- Add line
- :recycle: refactored CollaborateWithKodemia section into companies page
- :recycle: refactored NextDeveloper section into companies page
- :recycle: refactored NextDeveloper section into companies page
-  remove bulma in login
- fix toast
- :pencil2: fixed typos into InfoBullet component and other sections that include it
- fix bg-color and bg-image
- Update components/Pages/Login/LoginForm.tsx
- fix outline on input
-  form
- :recycle: refactored Hero section into home page, HeroCard and BgVideo components
- :lipstick: fix height for EventCards into Events page
- apply form
- Company Form
- add outline
- update names
- :recycle: refactored Hero section into javascript page, HeroJsInfo component
- :recycle: refactored Hero Js section and HeroJsInfo component
- :lipstick: deleted .scss files
- Change styles to tailwind classes
- Fix quotation marks and max width value
- :lipstick: fix Hero content overflow
- remove column class
- :lipstick: fix Hero content overflow into Home page
- :lipstick: fix background position in KodemiaFinancing component
- :lipstick: fixed responsive background position in KodemiaFinancing component
- :lipstick: updated origin from background videos into Home and Javascript pages
- Adjust code format and correct use of classNames
- :recycle: refactored Hero companies section
- :construction: refactor Hero companies section in progress

## PR Description

## Additional

### Screen Shots/Recordings

### Related Issues/Tickets

## Notes

Be sure to add if needed

- Tests
- Types
- Documentation

2022-03-15 08:44 UTC, devCharles requested changes
Se rompe en este tamaño ...

![Screen Shot 2022-03-15 at 2 43 39](https://user-images.githubusercontent.com/7495937/158339372-8073a215-61fb-48e4-915a-0284421cd2e3.png)

2022-03-15 08:46 UTC, devCharles commented
> Se rompe en este tamaño ...
> 
> ![Screen Shot 2022-03-15 at 2 43 39](https://user-images.githubusercontent.com/7495937/158339372-8073a215-61fb-48e4-915a-0284421cd2e3.png)

Olvidalo, es culpa de la seccion que aun no es migrada 😅 podemos ignorarlo por ahora

2022-03-15 08:47 UTC, devCharles approved these changes

2022-03-16 04:51 UTC, arianaomi commented
Rose al video le falta la opacidad cuando no se le da play

2022-03-16 05:18 UTC, evcorona approved these changes
👍🏼

2022-03-16 17:11 UTC, arianaomi commented
Rose creo faltaria ponerle mas espacio entre el boton y el texto para tratar que ocupe el mismo alto que el video.
![Screen Shot 2022-03-16 at 11 05 29](https://user-images.githubusercontent.com/14032235/158647898-17e58dc2-5979-4a3d-80bc-8bc3b08ed288.png)

![Screen Shot 2022-03-16 at 11 05 36](https://user-images.githubusercontent.com/14032235/158647912-23938c47-0c5d-4ed4-bdd1-bc0ab6becdc6.png)

2022-03-18 09:50 UTC, devCharles approved these changes

2022-03-18 20:30 UTC, arianaomi approved these changes
🚀

2022-03-18 20:35 UTC, merged