Clases page tailwind migration
kodemia/website.kodemia.mx pull request #156
Opened 2022-03-16 13:46 UTC by devCharles

2022-03-16 19:08 UTC, evcorona requested changes
Se rompe en pantallas grandes

https://user-images.githubusercontent.com/73207023/158668130-df05893e-84f5-4381-948c-2e6e8b76a3e8.mov

2022-03-16 19:08 UTC, evcorona commented on pages/clases.tsx
> +        subTitle='Clases kodemia'
Falta capitalizar el nombre de la escuela, 'Kodemia' en lugar de 'kodemia'

2022-03-17 06:21 UTC, arianaomi reviewed
El background debe ser mas claro que el footer (a mi me gusta como se ve asi  todo del mismo color)

2022-03-19 03:48 UTC, devCharles commented
> El background debe ser mas claro que el footer (a mi me gusta como se ve asi todo del mismo color)

El footer estaba de color erroneo, arreglado

2022-03-23 05:19 UTC, rrortegaa approved these changes

2022-03-23 09:07 UTC, devCharles commented on pages/clases.tsx
> +        subTitle='Clases kodemia'
Listo!

2022-03-23 16:06 UTC, arianaomi approved these changes

2022-03-23 22:14 UTC, evcorona approved these changes

2022-03-23 22:27 UTC, merged