full are you ready component
kodemia/website.kodemia.mx pull request #16
Opened 2020-11-06 04:20 UTC by arianaomi

- Sección " ¿Listo para ... ?

2020-11-06 05:06 UTC, rrortegaa approved these changes
:rocket:

2020-11-06 05:52 UTC, devCharles approved these changes

2020-11-06 05:54 UTC, devCharles requested changes

2020-11-06 05:54 UTC, devCharles commented on styles/pages/home/transform-your-life.scss
> +  margin: 45px 0;
Este margin genera una linea negra arriba del componente, creo que esto no va 🤔

2020-11-10 01:32 UTC, devCharles approved these changes

2020-11-10 01:38 UTC, merged