Button component
kodemia/website.kodemia.mx pull request #2
Opened 2020-10-09 21:40 UTC by arianaomi

2020-10-10 07:55 UTC, devCharles requested changes

2020-10-10 07:55 UTC, devCharles commented on components/Button.tsx
> +  type: string,
Creo que no debería existir un type, me parece mas descriptivo que tengamos props como `isPrimary` e `isSecondary` y poner las clases condicionalmente para cada uno

Para manejar mejor las clases condicionales podemos ocupar [esta lib](https://www.npmjs.com/package/classnames) para no hacerlo todo a "mano"

2020-10-10 07:55 UTC, devCharles commented on components/Button.tsx
> +  console.log(type)
Console.log() 👀

2020-10-10 07:55 UTC, devCharles commented on components/footer.tsx
> +    <footer className=' footer'>
aquí hay un espació vacio antes de footer

2020-10-10 07:55 UTC, devCharles commented on styles/components/button.scss
> +%button {
👍🏼 🔥

2020-10-10 07:56 UTC, devCharles commented
Falta el story del footer, para poder verlo

2020-10-13 22:08 UTC, devCharles requested changes

2020-10-13 22:08 UTC, devCharles commented on components/Button.tsx
> +export const Button: React.FC<ButtonProps> = ({
El React.FC para que es?

2020-10-13 22:08 UTC, devCharles commented on components/Button.tsx
> +    'button-white': hasWhiteBg
La clase white deberia ser un modificador del boton, deberia poder convivir con button-primary y con button-secondary

2020-10-13 22:08 UTC, devCharles commented on styles/components/button.scss
> +    border: 2px solid $cyan-primary;
Estas repitiendo border en cada clase y lo unico que cambia es el border color

Podrias abstraerlo para que en %button tengas: 
```scss
border-width: 2px;
border-style: solid;
```
y en cada una de las clases solo cambies el `border-color` asi es mas claro

2020-10-13 22:17 UTC, arianaomi commented on components/Button.tsx
> +    'button-white': hasWhiteBg
okis

2020-10-13 22:17 UTC, arianaomi commented on styles/components/button.scss
> +    border: 2px solid $cyan-primary;
ok si me parece mejor

2020-10-14 21:16 UTC, devCharles commented on components/Button.tsx
> +export const Button: React.FC<ButtonProps> = ({
Lo que deberiamos tipar aqui es el objeto de props, tipar el componente esta un poco de mas

2020-10-15 08:50 UTC, devCharles commented on components/Button.tsx
> +    'button-ikon': true,
Buen toque xD

2020-10-15 08:51 UTC, devCharles approved these changes

2020-10-16 06:38 UTC, merged