login
kodemia/website.kodemia.mx pull request #24
Opened 2021-01-11 18:02 UTC by arianaomi

2021-01-11 18:56 UTC, devCharles requested changes

2021-01-11 18:56 UTC, devCharles commented on lib/api.js
> +const baseURL = 'https://api-kodemia-mx.vercel.app'
Esta debería estar guardada en una variable de entorno, para que podamos tener diferentes ambientes en algún momento

2021-01-11 18:56 UTC, devCharles commented on pages/login.tsx
> +  }
Esta función si debería estar dentro del componente del formulario, no es necesario pasarla desde arriba si nunca va a cambiar

Si agregamos esta función al componente de login, el formulario queda suficientemente encapsulado para ser re-usado sin problema

2021-01-11 18:58 UTC, devCharles commented
Me gusta el scroll, pero en el login no deberíamos tener scroll, no debería mostrarse en la pagina de login

2021-01-12 04:25 UTC, rrortegaa commented on components/Pages/Login/LoginForm.tsx
> +export interface Data{
Dejar un espacio aquí entre Data y {

2021-01-12 04:42 UTC, rrortegaa commented on styles/pages/login/login.scss
> +          width: 340px;
Agregar un margin-top: 25px; para que el form no esté tan cerca de Bienvenido

2021-01-12 05:10 UTC, rrortegaa submitted a review, later dismissed

2021-01-12 07:04 UTC, devCharles commented
@arianaomi la barra del scroll aun se ve en la pagina de login, podemos quitarla con css porfa?

2021-01-12 08:08 UTC, devCharles commented
@arianaomi puedes borrar los dos puntos de usuario y contraseña porfa?

2021-01-12 20:42 UTC, devCharles requested changes

2021-01-12 20:42 UTC, devCharles commented on next.config.js
> +    URL_API: 'https://api-kodemia-mx.vercel.app'
Aquí no debería el valor de la variable, debería tomar el valor del proceso así:
```
URL_API: process.env.URL_API
```

2021-01-12 20:42 UTC, devCharles commented on styles/index.scss
> +    background: $white-lighter;
Podemos hacer el background negro porfa? de este color llama mucho la atención 🤔

2021-01-12 20:42 UTC, devCharles commented on styles/index.scss
> +    width: 10px;
yo creo que un width mas pequeño, de 4px se ve bien

2021-01-12 20:42 UTC, devCharles commented on styles/index.scss
> +    background: rgba(0, 255, 255, 0.5);
Este color se ve mejor en gris oscuro, para que no resalte tanto la barra de scroll

2021-01-12 20:43 UTC, devCharles commented
En mobile tenemos este problema: 
![photo_2021-01-12 14 43 02](https://user-images.githubusercontent.com/7495937/104370467-85dc0e00-54e4-11eb-9fd3-5de8b745fd82.jpeg)

2021-01-12 21:59 UTC, arianaomi commented on styles/index.scss
> +    width: 10px;
Al hacerla delgada es difícil seleccionarlo (aunq no se si eso sea importante) creo que 6px podría funcionar aun se ve delgada y se puede seleccionar mejor

2021-01-13 06:18 UTC, devCharles approved these changes
![launch](https://user-images.githubusercontent.com/7495937/104413928-e2ffb000-5534-11eb-961a-d75fcb0a8541.gif)

2021-01-13 15:25 UTC, merged