Hero Seccion ( Bootcamps)
kodemia/website.kodemia.mx pull request #26
Opened 2021-01-15 01:38 UTC by arianaomi

-  Built hero secction.
- ADD testimonials and TransformYourLife sections

2021-01-15 04:02 UTC, rrortegaa commented on components/Pages/Bootcamps/HeroCard.tsx
> +          <H3 text='Javascript' />
_Aquí hay que preguntar por el copy correcto, en desktop aparece como Javascript pero en tablet y mobile aparece como Web developer_

2021-01-15 04:05 UTC, rrortegaa approved these changes

2021-01-15 20:38 UTC, rrortegaa requested changes

2021-01-15 20:38 UTC, rrortegaa commented on components/Pages/Bootcamps/HeroCard.tsx
> +          <H1 text='Bootcamp Full Stack JavaScript' />
_Este copy aparece en Figma como "Bootcamp Full Stack con Javascript"_ :eyes:

2021-01-15 20:45 UTC, rrortegaa commented on components/Pages/Bootcamps/HeroCard.tsx
> +          <H3 text='Javascript' />
Según comenta Lucy, el copy correcto es el de desktop :cool: :smile:

2021-01-15 20:56 UTC, rrortegaa approved these changes

2021-01-16 05:42 UTC, devCharles approved these changes

2021-01-16 05:43 UTC, devCharles commented
![launch](https://user-images.githubusercontent.com/7495937/104798311-6adef780-578b-11eb-977a-85e5364bb3ab.gif)

2021-01-18 17:33 UTC, merged