apply form
kodemia/website.kodemia.mx pull request #28
Opened 2021-01-19 08:22 UTC by devCharles

2021-01-19 22:44 UTC, arianaomi reviewed
- En tablet el padding horizontal no es el mismo.
- en ¿Qué programa te interesa? se seguira mostrando lifetime ¿?

2021-01-19 22:53 UTC, arianaomi commented on components/ApplyForm.tsx
> +        Al enviar este formulario estas aceptando nuestros <Link href='/'> Terminos y conidiciónes </Link>
se te fue una i de más y falta el ´ en  la e de términos

2021-01-20 04:41 UTC, devCharles commented
> * En tablet el padding horizontal no es el mismo. <- Cual padding? @arianaomi 
> * en ¿Qué programa te interesa? se seguira mostrando lifetime ¿?, nop, ahora lo quitó 😄

2021-01-20 04:48 UTC, arianaomi commented
![Captura de Pantalla 2021-01-19 a la(s) 22 45 57](https://user-images.githubusercontent.com/14032235/105128314-66c31a80-5aa8-11eb-8265-5d5ee8c70bdf.png)
![Captura de Pantalla 2021-01-19 a la(s) 22 45 46](https://user-images.githubusercontent.com/14032235/105128326-6f1b5580-5aa8-11eb-9e91-4229948d0839.png)

El form no respeta el padding

2021-01-20 04:55 UTC, rrortegaa commented on schemas/applyForm.schema.ts
> +      console.log('value: ', value)
aqui!

2021-01-20 05:07 UTC, devCharles commented on components/ApplyForm.tsx
> +        Al enviar este formulario estas aceptando nuestros <Link href='/'> Terminos y conidiciónes </Link>
Listo

2021-01-20 05:09 UTC, devCharles commented on schemas/applyForm.schema.ts
> +      console.log('value: ', value)
Listo

2021-01-20 06:59 UTC, devCharles commented
@arianaomi resuelto, eran 12 px 😄  gracias, buen ojo ahí

2021-01-20 07:53 UTC, arianaomi commented
<img width="871" alt="Captura de Pantalla 2021-01-20 a la(s) 1 50 49" src="https://user-images.githubusercontent.com/14032235/105143833-0214b980-5ac2-11eb-85a3-45812fafeb5c.png">

Esto es en 769px (tablet), creo que es esto quien lo provoca margin-left: 60px

2021-01-20 18:18 UTC, rrortegaa commented on components/ApplyForm.tsx
> +        Al enviar este formulario estas aceptando nuestros <Link href='/terminos-y-condiciones'> Términos y conidiciónes </Link>
A "conidiciónes" le sobra una i  aún

2021-01-20 18:22 UTC, rrortegaa reviewed
Te dejé un comment en ApplyForm 😅

2021-01-20 18:56 UTC, rrortegaa commented
> <img alt="Captura de Pantalla 2021-01-20 a la(s) 1 50 49" width="871" src="https://user-images.githubusercontent.com/14032235/105143833-0214b980-5ac2-11eb-85a3-45812fafeb5c.png">
> 
> Esto es en 769px (tablet), creo que es esto quien lo provoca margin-left: 60px

**Si, ese margin podría quedar como margin-left: 1rem;**

2021-01-20 19:09 UTC, rrortegaa commented on styles/pages/aplicar/index.scss
> +      padding: 20px;
_En este padding en mobile podría verse mejor padding: 20px 15px;_
_¿Qué opinas?_

![image](https://user-images.githubusercontent.com/20275714/105222743-826a0780-5b20-11eb-9e66-5f3d240f896f.png)

2021-01-20 19:10 UTC, rrortegaa reviewed
Te dejé otro par de comentarios

2021-01-22 01:07 UTC, rrortegaa requested changes
🔖

2021-01-22 07:05 UTC, arianaomi approved these changes

2021-01-22 07:19 UTC, rrortegaa approved these changes
🚀 🚀

2021-01-22 07:19 UTC, merged