Footer component
kodemia/website.kodemia.mx pull request #4
Opened 2020-10-13 00:32 UTC by arianaomi

2020-10-13 20:16 UTC, rrortegaa requested changes
Nao, te dejé algunos comentarios en el código.
Y aquí te agrego otro más referente a los botones, en el cambio de tablet a desktop los botones muestran el contenido en dos líneas, tal vez para evitar esto habría que checar el tamaño de la letra o revisar los padding; de hecho, me parece que los botones deben ser ligéramente menos altos.

2020-10-13 22:19 UTC, arianaomi commented on styles/components/footer.scss
> +    text-decoration: none;
si creo que es lo mejor porq en todos se trabaja así

2020-10-13 22:21 UTC, arianaomi commented on components/Footer.tsx
> +          <p>Teléfonos 55 3731 72 66</p>
Gracias

2020-10-15 22:15 UTC, rrortegaa commented on styles/components/button.scss
> +  border-color: $cyan;
👍

2020-10-16 07:09 UTC, devCharles approved these changes

2020-10-16 07:10 UTC, merged