FIX: video position of the current class
kodemia/website.kodemia.mx pull request #41
Opened 2021-01-27 20:39 UTC by arianaomi

- fixing position 
- adding correct image in classes

2021-01-27 22:16 UTC, rrortegaa requested changes
Nao, te deje unos comments

2021-01-27 22:16 UTC, rrortegaa commented on styles/pages/classes/klass.scss
> +
En Mobile, la información en .video-data-btns debería estar alineada a la izquierda y no centrada, para que no se vea mal en las pantallas más pequeñas podría agregarse flex-wrap: wrap para que los elementos se acomoden en columna en este caso.

2021-01-27 22:16 UTC, rrortegaa commented on styles/pages/classes/klass.scss
> +
a partir de tablet hacía abajo, se necesita agregar un mb-5 aprox. en .video-data-btns

2021-01-28 08:24 UTC, rrortegaa commented on styles/pages/classes/klass.scss
> +          //flex-direction: column;
Eliminar este comment 😉

2021-01-28 09:10 UTC, rrortegaa requested changes
- _No había visto que en mobile los botones (btn-ikon) no quedan alineados a la izquierda del todo, me parece que quitando margin-left del primero y margin-right del segundo se alinean correctamente a la izquierda en las pantallas más pequeñas y a la derecha en las más grandes de mobile o la alternativa podría ser darle un tamaño aprox. de 180px al container-btns, ponerle un justify-content: space-between y también darle a este contenedor de los botones un margin-top de 20px aprox. porque están muy cerca de la fecha. Ah! y quitar el margin a los botones_

![image](https://user-images.githubusercontent.com/20275714/106112882-67e0f100-6113-11eb-819c-d6015ba29f21.png)

- _En video-data-buttons ¿Son necesarios la alineación y el justificado?_ 🤔

2021-01-29 04:10 UTC, rrortegaa approved these changes

2021-01-29 16:11 UTC, devCharles approved these changes
![launch](https://user-images.githubusercontent.com/7495937/106299024-49b1e880-621a-11eb-87f3-37eabd832916.gif)

2021-01-29 18:15 UTC, merged