Ready
kodemia/website.kodemia.mx pull request #48
Opened 2021-02-04 20:00 UTC by arianaomi

- ready to find the next-developer ... ? section

2021-02-05 03:49 UTC, devCharles approved these changes

2021-02-05 03:54 UTC, devCharles requested changes

2021-02-05 03:54 UTC, devCharles commented on components/Pages/Companies/NextDeveloper.tsx
> +import H2 from '../../H2'
Ya no deberiamos usar esta forma de importar, 

Agregue al archivo de configuración de TS la configuración del basedir, puedes/debes poner el nombre de la carpeta directamente, asi los componentes ya no dependen de estar especificamente en una carpate, puden ser movidos de carpeta y aun funciona todo

Esto quedaria así 
```suggestion
import Button from 'components/Button'
import H2 from 'components/H2'
```

Lo mismo en los de mas archivos

2021-02-05 04:08 UTC, devCharles requested changes

2021-02-05 04:08 UTC, devCharles commented on pages/empresas.tsx
> +import NextDeveloper from '../components/Pages/Companies/NextDeveloper'
Lo mismo de los imports aquí, puedes actualizar todos los de este archivo porfa?

2021-02-05 04:50 UTC, arianaomi commented on pages/empresas.tsx
> +import NextDeveloper from '../components/Pages/Companies/NextDeveloper'
okis, los cambio

2021-02-05 07:51 UTC, devCharles approved these changes

2021-02-06 00:50 UTC, rrortegaa approved these changes

2021-02-06 01:25 UTC, rrortegaa approved these changes

2021-02-06 01:27 UTC, merged