Why choose a koder
kodemia/website.kodemia.mx pull request #52
Opened 2021-02-09 21:48 UTC by arianaomi

- ADD choose a koder section

2021-02-10 01:07 UTC, rrortegaa requested changes
Nao, con los íconos hay que ponernos de acuerdo dónde los vamos a guardar,  hemos venido colocándolos en public/icons indistintamente de la vista en la que van, aquí los guardaste en public/images/companies 🤔 👀

2021-02-11 04:01 UTC, rrortegaa approved these changes

2021-02-11 22:37 UTC, devCharles commented
@arianaomi falta cambiar el cursor en el hoover del nombre del programa y en la barra para que el usuario sepa que se le puede dar click

2021-02-11 23:25 UTC, devCharles requested changes

2021-02-13 01:15 UTC, devCharles approved these changes

2021-02-13 01:15 UTC, devCharles commented
![launch](https://user-images.githubusercontent.com/7495937/107837484-a3f89080-6d66-11eb-9362-691d655f4a52.gif)

2021-02-13 01:23 UTC, rrortegaa approved these changes
🚀

2021-02-13 02:06 UTC, merged