Companies form
kodemia/website.kodemia.mx pull request #57
Opened 2021-02-16 03:04 UTC by arianaomi

- ADD register company form

2021-02-16 18:19 UTC, devCharles requested changes

2021-02-16 18:19 UTC, devCharles commented on components/Pages/Companies/RegisterFrom.tsx
> +        router.push('empresas/gracias')
Aquí le falta un slash, al inicio si no falla la re dirección
o le pones el slash o solo le dejas `router.push('gracias')` pero así como esta nos da 404
![Captura de Pantalla 2021-02-16 a la(s) 12 13 51](https://user-images.githubusercontent.com/7495937/108104434-ec5acb80-7050-11eb-8454-86808e57c66a.png)

2021-02-16 23:50 UTC, rrortegaa commented on schemas/registerCompanyForm.schema.ts
> +  company: z.string().min(2, { message: ' Ingresa el nombre de tu compañiaa' }),
_Nao, en compañía sobra una a_

2021-02-16 23:50 UTC, rrortegaa commented on lib/api.ts
> +  const url = 'active-campaign/companies'
🤔  _Parece que aquí a la url le falta / al principio_

2021-02-16 23:50 UTC, rrortegaa commented on components/Pages/Companies/RegisterFrom.tsx
> +        router.push('empresas/gracias')
_Nao, ¿El nombre de este archivo debería ser RegisterForm o RegisterFrom?_

2021-02-17 23:22 UTC, rrortegaa approved these changes
🚀

2021-02-20 01:49 UTC, devCharles approved these changes

2021-02-20 01:53 UTC, merged