InfoCard component
kodemia/website.kodemia.mx pull request #6
Opened 2020-10-15 21:49 UTC by arianaomi

2020-10-21 14:47 UTC, rrortegaa commented on styles/components/infoCards.scss
> +  padding-right: 20px;
el padding ya está definido en 20px en la línea 6, es necesaria ésta línea?

2020-10-21 16:17 UTC, rrortegaa requested changes
Nao, te dejé un par de comentarios en el código

2020-10-21 16:17 UTC, rrortegaa commented on styles/components/index.scss
> +@import './infoCards';
Sería bueno cambiar el nombre de este scss considerando la recomendación de usar nombres en minúsculas con guiones para la separación, i.e. info-card. 
¿El plural "Cards" es por algo en particular? 🤔

2020-10-22 01:35 UTC, devCharles commented on pages/index.js
> +      <InfoCard icon='/icons/Icon-Objetivo.svg' title='Te acompañamos en el proceso' description='Todos los días, por módulos y por Bootcamp, llevarás proyectos prácticos reales' />
Esta linea esta muy larga, hay que partirla

```suggestion
      <InfoCard 
        icon='/icons/Icon-Objetivo.svg' 
        title='Te acompañamos en el proceso'
        description='Todos los días, por módulos y por Bootcamp, llevarás proyectos prácticos reales'
      />
```

2020-10-22 04:20 UTC, rrortegaa approved these changes
:+1:  :rocket:

2020-10-22 06:15 UTC, devCharles approved these changes

2020-10-22 06:23 UTC, merged