fix max-width
kodemia/website.kodemia.mx pull request #62
Opened 2021-03-01 20:51 UTC by arianaomi

- just change the value of content-max-width

2021-03-01 21:21 UTC, rrortegaa commented on styles/pages/companies/index.scss
> +@import 'registro';
si seguimos con los nombres de los archivos y carpetas de estilos en ingles, este también debería estar en inglés

2021-03-01 21:23 UTC, rrortegaa submitted a review, later dismissed

2021-03-02 17:34 UTC, rrortegaa requested changes

2021-03-03 08:44 UTC, rrortegaa requested changes

2021-03-03 08:44 UTC, rrortegaa commented on styles/components/navbar.scss
> +    padding: 12px 70px;
- _En tablet y mobile ocurre que la hamburguesa queda un poco dentro de la alineación derecha de las secciones y el logo sale un poco de la alineación izquierda, haciendo estos dos cambios me parece que queda mejor:_

_Cambiando el padding a:_
```
@include on-mobile {
    padding: 5px 33px;
 }

 @include on-tablet {
     padding: 12px 72px;
  }
```
_y sobreescribiendo con width: 2.75rem:_

``` 
.navbar-burger {
    width: 3.25rem;
}
```

- _Todavía falta alinear las vistas de los formularios  con el navbar_

2021-03-04 20:46 UTC, devCharles approved these changes

2021-03-05 01:19 UTC, rrortegaa approved these changes

2021-03-05 04:02 UTC, merged