Update video into companies Hero  component
kodemia/website.kodemia.mx pull request #64
Opened 2021-03-03 07:03 UTC by rrortegaa

- **Video in companies hero updated**

2021-03-03 19:49 UTC, arianaomi commented on components/Pages/Companies/Hero.tsx
>            />
aquí porque lo separaste en dos H2 ?

2021-03-09 09:47 UTC, devCharles requested changes
Quitar el outline del video cuando esta en estado `focus`

2021-03-11 16:36 UTC, arianaomi submitted a review, later dismissed
🚀

2021-03-11 18:31 UTC, arianaomi submitted a review, later dismissed

2021-03-11 19:24 UTC, arianaomi approved these changes
🔄 🚀

2021-03-11 21:34 UTC, devCharles approved these changes

2021-03-11 21:59 UTC, merged