Sign out
kodemia/website.kodemia.mx pull request #65
Opened 2021-03-05 08:26 UTC by arianaomi

- add "Cerrar sesión" button
- check  token

2021-03-05 23:32 UTC, devCharles requested changes

2021-03-05 23:32 UTC, devCharles commented on pages/clase.tsx
> +        if (status === 401) {
Esta cool para los 401 pero, que pasa cuando falla con otro status? 

Hay que mostrar un msj generico para los otros casos

2021-03-09 00:20 UTC, devCharles approved these changes

2021-03-09 00:33 UTC, rrortegaa approved these changes

2021-03-09 01:37 UTC, merged