Font size
kodemia/website.kodemia.mx pull request #67
Opened 2021-03-12 20:16 UTC by arianaomi

- change the font-size value in all views.

2021-03-21 07:00 UTC, devCharles requested changes

2021-04-08 00:30 UTC, devCharles submitted a review, later dismissed

2021-04-08 02:40 UTC, rrortegaa commented on components/Pages/Bootcamps/Certifications.tsx
> +  certifications: Array<Certification>
Nao, este espacio sigue apareciendo

2021-04-08 03:24 UTC, rrortegaa approved these changes
🚀 🚀 🚀

2021-04-08 03:31 UTC, merged