Bootcamp type card
kodemia/website.kodemia.mx pull request #8
Opened 2020-10-20 05:23 UTC by arianaomi

2020-10-21 16:23 UTC, rrortegaa requested changes

2020-10-21 16:23 UTC, rrortegaa commented on styles/components/bootcampCard.scss
> +  border: solid 1px $text;
¿Crees que convendría usar como nombres de variables para estos colores algo estilo $cyan-text o $gray-info? 🤔

2020-10-21 22:16 UTC, arianaomi commented on styles/components/bootcampCard.scss
> +  border: solid 1px $text;
si, creo que es mas descriptivo

2020-10-22 02:07 UTC, devCharles requested changes

2020-10-22 02:07 UTC, devCharles commented on components/BootcampCard.tsx
> +  feature: string
string no String

2020-10-22 02:07 UTC, devCharles commented on styles/variables.scss
> +$text-gray: $gray;
Aqui no debemos renombrar estas porque asi como lo tenias estabas sobreescribiendo las de bulma y eso era justo lo que queriamos

2020-10-22 02:07 UTC, devCharles commented on stories/BootcampCard.stories.tsx
> +import { Story, Meta } from '@storybook/react/types-6-0'
importa mejor solo de `@storybook/react`

2020-10-22 02:07 UTC, devCharles commented on stories/BootcampCard.stories.tsx
> +// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
Este comentario no deberia estar

2020-10-22 02:07 UTC, devCharles commented on styles/components/navbar.scss
> -        // }
Porque esta comentado esto? es codigo muerto? si si hay que quitarlo

2020-10-22 04:38 UTC, rrortegaa approved these changes
:rocket: :rocket:

2020-10-22 06:17 UTC, devCharles approved these changes

2020-10-22 06:24 UTC, merged