new inputs
kodemia/website.kodemia.mx pull request #83
Opened 2021-07-27 05:03 UTC by arianaomi

- Add new form inputs

2021-07-27 15:09 UTC, devCharles requested changes

2021-07-27 15:09 UTC, devCharles commented on components/ApplyForm.tsx
> +            { value: 'no, vengo de cero' }
Estos también deberían empezar en mayuscula

2021-07-27 15:09 UTC, devCharles commented on schemas/applyForm.schema.ts
> -
Hay que dejar una linea en blanco en cada archivo al inicio, para que no este pegado todo hasta arriba

2021-07-27 22:59 UTC, arianaomi commented on components/ApplyForm.tsx
> +            { value: 'no, vengo de cero' }
Los habia puesto así porq así estan en AC, pero ya les puse el label para que se muestren bien

2021-07-28 14:43 UTC, devCharles approved these changes

2021-07-28 14:43 UTC, devCharles commented on schemas/applyForm.schema.ts
> +  //course: z.enum(["javascript-live"]),
Se ve bien, solo hay que borrar esta linea y podemos dar merge

2021-07-28 15:49 UTC, merged