Hero
kodemia/website.kodemia.mx pull request #9
Opened 2020-10-22 19:52 UTC by arianaomi

Secciónn hero y los componentes de titulos

2020-10-23 01:05 UTC, devCharles commented on components/Cursor.tsx
> +
Me imaginaba diferente este componente

Yo pensaba crear un componente `cursorText` que englobara la lógica que pusiste en `H1` y `H2` 

Esta logica
```
  const finalPosition = title.length - 1
  const newTitle = title.slice(0, finalPosition)
  const character = title[finalPosition]
````
Para no duplicar esa misma lógica en `H1` y `H2` y entonces ocupar este componente en esos

2020-10-23 01:05 UTC, devCharles commented on components/H1.tsx
> +}: Props) {
Si solo es un prop no es necesario que se deconstruya en varias lineas

2020-10-23 01:05 UTC, devCharles commented on components/H1.tsx
> +  title: string
Creo que `text` es un nombre de prop mas apropiado, porque ya es un header

Si le pones title, me hace pensar que hay un text también

2020-10-23 05:05 UTC, arianaomi commented on components/Cursor.tsx
> +
osea el componente cursorText tendría la lógica y solo se mandaría a llamar en H1 
```
<h1> <CursorText text = {text} /> <h1/>

2020-10-23 05:23 UTC, rrortegaa commented on styles/components/footer.scss
> +    grid-template-columns: repeat(2, 1fr);
:wink:

2020-10-23 05:35 UTC, rrortegaa commented on components/Pages/Home/Hero.tsx
> +          src='/icons/Button-Telegram.svg' className='arrow-icon'
¿El Icon-Scroll.svg es el ícono que va aquí o no nos compartieron el correcto?

2020-10-23 05:54 UTC, arianaomi commented on components/Pages/Home/Hero.tsx
> +          src='/icons/Button-Telegram.svg' className='arrow-icon'
si, pero como aun no hacia merge con las rama que tenia todos puse ese temporal y aun no lo cambio

2020-10-23 20:13 UTC, arianaomi commented on components/Cursor.tsx
> +
ya ahora si, solo exite un componente con la logica, pero tuve que crear dos h2 para poder manejar el estilo

2020-10-24 03:08 UTC, rrortegaa approved these changes
:+1: :rocket:

2020-10-25 07:29 UTC, devCharles approved these changes

2020-10-26 20:18 UTC, rrortegaa requested changes

2020-10-26 20:18 UTC, rrortegaa commented on styles/components/text-cursor.scss
> +  border-bottom: 2px solid;
¿Qué te parece con un border bottom a 3px? :thinking:

2020-10-26 21:03 UTC, arianaomi commented on styles/pages/Home/hero.scss
> +        bottom: -110px;
Para modificar eso tuve que cambiar el padding que le estaba dando en tablet.

2020-10-27 04:45 UTC, rrortegaa approved these changes
:superhero_woman::rocket:

2020-10-27 05:08 UTC, devCharles approved these changes

2020-10-27 05:09 UTC, merged