Eventos
kodemia/website.kodemia.mx pull request #98
Opened 2021-11-06 11:05 UTC by arianaomi

- Add events page

2021-11-08 22:10 UTC, devCharles requested changes

2021-11-08 22:10 UTC, devCharles commented on tailwind.config.js
> +        mobile: "url('https://s3.us-east-2.amazonaws.com/cdn.kodemia.mx/images/eventos/eventos-mobile.jpg')"
aquí "mobile" no me dice mucho

2021-11-08 22:10 UTC, devCharles commented on tailwind.config.js
> +        'events-mobile': "url('https://s3.us-east-2.amazonaws.com/cdn.kodemia.mx/images/eventos/eventos-mobile.jpg')"
Recuerda que las urls del cdn empiezan con cdn.kodemia.mx no es toda la url del s3

2021-11-08 22:10 UTC, devCharles commented on pages/eventos.tsx
> +}
La indentación del proyecto es a 2 espacios

2021-11-08 22:10 UTC, devCharles commented on tailwind.config.js
> +        'sm-kd': '220px',
esta coma esta de mas

2021-11-08 22:10 UTC, devCharles commented on pages/eventos.tsx
> +	const results = await builder.getAll('evento', { limit: 10 })
por que ponemos un limit de 10?
podemos dejarlo sin limite?

2021-11-08 22:10 UTC, devCharles commented on components/Card.tsx
> +import Button from './Button'
Recuerda que las rutas deben ser relativas al root del proyecto no al componente actual

2021-11-08 23:28 UTC, rrortegaa reviewed
👀

2021-11-11 16:31 UTC, devCharles approved these changes

2021-11-11 16:44 UTC, merged